### ISSUE TITLE
Project cannot be compiled with maven

### ISSUE THREAD

**Issue by Venca24** [kaderavaclav/pa165-machine-rental#61]
Po zadání příkazu "mvn clean install" končí s chybou "error: unmappable character for encoding UTF8" v UserDao.java, v RentalUser.java i v RentDaoTest.java, pravděpodobně i v jiných.

**Comment by kaderavaclav** [comment]
Právě jsem stáhnul ZIP repozitáře a spustil `mvn clean install` a Build SUCCESS ... za vteřinu vložím výstřižek

**Comment by Venca24** [comment]
@kaderavaclav Používáš Windows?

**Comment by kaderavaclav** [comment]
ano Windows 10 ... výstřižek zde: http://prnt.sc/d2a4mi

**Comment by kaderavaclav** [comment]
@Venca24 na jaké verzi maven to spouštíš? ... moje konfigurace viz http://prnt.sc/d2a6mp

**Comment by Venca24** [comment]
Můj výstup z mvn clean install (znovu jsem stáhl z githubu, spustil jsem v kořenovém adresáři repo):
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.0.2:compile (default-compile) @ persistance ---
[INFO] Compiling 13 source files to /tmp/pa165-machine-rental/persistance/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] pa165-machine-rental .............................. SUCCESS [0.348s]
[INFO] persistance ....................................... FAILURE [0.799s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.264s
[INFO] Finished at: Wed Nov 02 20:45:23 CET 2016
[INFO] Final Memory: 13M/165M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project persistance: Compilation failure: Compilation failure:
[ERROR] /tmp/pa165-machine-rental/persistance/src/main/java/cz/muni/fi/pa165/machrent/entities/RentalUser.java:[11,47] error: unmappable character for encoding UTF8
[ERROR] 
[ERROR] /tmp/pa165-machine-rental/persistance/src/main/java/cz/muni/fi/pa165/machrent/dao/UserDao.java:[52,27] error: unmappable character for encoding UTF8

Já mám Apache Maven 3.0.5 a Java 1.8.0_101 od Oracle.

Tipoval bych, že ty soubory jsou uložené v nějakém windowsovském kódování, ale maven jako výchozí používá UTF-8. Jiné než UTF-8 by mohlo jít nastavit v pom.xml, jinak uložit dotyčné soubory v UTF-8.

**Comment by kaderavaclav** [comment]
Pokusím se zjistit a dám vědět, jestli se to podaří... změny kdyžtak budou v branch `master-bugfix`

**Comment by kaderavaclav** [comment]
@Venca24 zkus nyní > [master-bugfix](https://github.com/kaderavaclav/pa165-machine-rental/tree/master-bugfix)

**Comment by Venca24** [comment]
@kaderavaclav 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project persistance: Compilation failure: Compilation failure:
[ERROR] /tmp/pa165-machine-rental/persistance/src/main/java/cz/muni/fi/pa165/machrent/entities/RentalUser.java:[11,47] error: unmappable character for encoding UTF8
[ERROR] 
[ERROR] /tmp/pa165-machine-rental/persistance/src/main/java/cz/muni/fi/pa165/machrent/dao/UserDao.java:[52,27] error: unmappable character for encoding UTF8

V tagu "project.build.sourceEncoding" by mělo být skutečné kódování těch souborů se zdrojáky. Podívej se v čem jsou.

**Comment by kaderavaclav** [comment]
@Venca24 opět změněno na 'Cp1250' což mi ukazuje `mvn -v` ... ale domnívám se, jestli není problém spíše s verzí Maven - uvádíš, že máš `3.0.5` a náš projekt je sestaven v `3.3.9`?

**Comment by kaderavaclav** [comment]
@Venca24 FYI mi po obou změnách vždy prošlo čistě `mvn clean install`, stejně tak jako mi před chvílí potvrdil @benusp, že mu to z NetBeans taky prochází

**Comment by Venca24** [comment]
@kaderavaclav Máš pravdu, v mavenu 3.3.9 to jde bez problémů. Vyřešeno.
